# ==============================================================================
# SCRIPT 01: QC, DOUBLET REMOVAL AND PRE-PROCESSING
# Dataset: GSE165816 - DFU scRNA-seq (Skin Biopsies)
#
# WORKFLOW PER SAMPLE:
#   1. Load raw counts
#   2. Compute QC metrics (nFeature, nCount, % mitochondrial)
#   3. Hard-threshold QC filter (nFeature 200-6000 | percent.mt < 20%)
#   4. Doublet detection with scDblFinder  [NEW]
#   5. Remove predicted doublets           [NEW]
#   6. Log-normalize + find HVGs
#   7. Merge all samples into one Seurat object
#   8. JoinLayers (Seurat v5) + ScaleData + PCA
#
# DEPENDENCIES:
#   BiocManager::install(c("scDblFinder", "SingleCellExperiment", "BiocParallel"))
#   install.packages(c("Seurat","ggplot2","dplyr","patchwork","stringr","tidyr"))
#
# PREREQUISITE: Script 00 completed successfully
# ==============================================================================

rm(list = ls())
set.seed(42)

library(Seurat)
library(scDblFinder)
library(SingleCellExperiment)
library(BiocParallel)
library(ggplot2)
library(dplyr)
library(tidyr)
library(patchwork)
library(stringr)

# ==============================================================================
# 0. DIRECTORY SETUP
# ==============================================================================
base_dir <- "~/federica.dannunzio@uniroma1.it - Google Drive/Drive condivisi/sc-FEDE_DAVIDE/res_validation/nature_paper_validation"
data_dir <- file.path(base_dir, "scRNA_data_new")
res_dir  <- file.path(base_dir, "res")
plot_dir <- file.path(res_dir, "plots", "QC")

dir.create(res_dir,  showWarnings = FALSE, recursive = TRUE)
dir.create(plot_dir, showWarnings = FALSE, recursive = TRUE)

# ==============================================================================
# GLOBAL PLOT THEME
# - Black axes and ticks
# - No background grid
# - All labels in English
# Applied to all ggplot2 outputs; Seurat outputs patched with seurat_theme()
# ==============================================================================
theme_dfu <- function(base_size = 12) {
  theme_classic(base_size = base_size) %+replace%
    theme(
      axis.line         = element_line(color = "black", linewidth = 0.5),
      axis.ticks        = element_line(color = "black"),
      axis.text         = element_text(color = "black"),
      axis.title        = element_text(color = "black"),
      panel.grid.major  = element_blank(),
      panel.grid.minor  = element_blank(),
      panel.background  = element_rect(fill = "white", color = NA),
      plot.background   = element_rect(fill = "white", color = NA),
      strip.background  = element_rect(fill = "grey92", color = "black", linewidth = 0.4),
      strip.text        = element_text(color = "black", face = "bold"),
      legend.background = element_rect(fill = "white", color = NA),
      legend.key        = element_rect(fill = "white", color = NA),
      legend.text       = element_text(color = "black"),
      legend.title      = element_text(color = "black", face = "bold"),
      plot.title        = element_text(face = "bold", color = "black", size = base_size + 1),
      plot.subtitle     = element_text(color = "grey35", size = base_size - 1),
      plot.caption      = element_text(color = "grey50",  size = base_size - 2)
    )
}

# Patch to apply on top of Seurat-generated ggplot objects
seurat_theme <- function() {
  theme(
    panel.background  = element_rect(fill = "white", color = NA),
    panel.grid.major  = element_blank(),
    panel.grid.minor  = element_blank(),
    axis.line         = element_line(color = "black", linewidth = 0.5),
    axis.ticks        = element_line(color = "black"),
    axis.text         = element_text(color = "black"),
    axis.title        = element_text(color = "black"),
    strip.background  = element_rect(fill = "grey92", color = "black"),
    strip.text        = element_text(color = "black", face = "bold"),
    legend.background = element_rect(fill = "white", color = NA),
    legend.key        = element_rect(fill = "white", color = NA),
    legend.text       = element_text(color = "black"),
    legend.title      = element_text(color = "black", face = "bold"),
    plot.title        = element_text(face = "bold", color = "black"),
    plot.subtitle     = element_text(color = "grey35")
  )
}

# Condition colours — consistent across all scripts
cond_colors <- c("Healing" = "#2196F3", "Non-Healing" = "#F44336", "Diabetes" = "#4CAF50")

# ==============================================================================
# 1. LOAD SAMPLE METADATA (generated by Script 00)
# ==============================================================================
gsm_mapping <- read.csv(file.path(base_dir,"samples_info", "gsm_mapping.csv"), stringsAsFactors = FALSE)
cat(sprintf("Samples in mapping: %d\n", nrow(gsm_mapping)))
print(table(gsm_mapping$Condition))

# ==============================================================================
# 2. FLEXIBLE LOADING FUNCTION
#    Supports: MatrixMarket (.mtx), compressed CSV/TSV (.csv.gz, .tsv.gz)
# ==============================================================================
load_sample <- function(gsm_id, data_dir) {
  gsm_dir   <- file.path(data_dir, gsm_id)
  if (!dir.exists(gsm_dir)) {
    message(sprintf("  [SKIP] %s - directory not found", gsm_id)); return(NULL)
  }
  all_files <- list.files(gsm_dir, full.names = TRUE, recursive = TRUE)

  # Case 1: MatrixMarket (10x Genomics)
  mtx_file <- all_files[grepl("\\.mtx(\\.gz)?$", all_files, ignore.case = TRUE)]
  if (length(mtx_file) > 0) {
    barcodes_file <- all_files[grepl("barcodes", all_files, ignore.case = TRUE)]
    features_file <- all_files[grepl("features|genes", all_files, ignore.case = TRUE)]
    if (length(barcodes_file) > 0 && length(features_file) > 0) {
      tryCatch({
        counts <- ReadMtx(mtx = mtx_file[1], cells = barcodes_file[1],
                          features = features_file[1])
        message(sprintf("  [OK] %s - MatrixMarket (%d genes, %d cells)",
                        gsm_id, nrow(counts), ncol(counts)))
        return(counts)
      }, error = function(e) {
        message(sprintf("  [ERROR] %s - ReadMtx failed: %s", gsm_id, e$message))
        return(NULL)
      })
    }
  }

  # Case 2: Compressed CSV/TSV
  csv_files <- all_files[grepl("\\.(csv|tsv|txt)(\\.gz)?$", all_files, ignore.case = TRUE)]
  csv_files <- csv_files[!grepl("metadata|meta|barcode|feature|gene_name",
                                 basename(csv_files), ignore.case = TRUE)]
  if (length(csv_files) > 0) {
    tryCatch({
      sep_char <- ifelse(grepl("\\.tsv", csv_files[1]), "\t", ",")
      counts   <- read.table(gzfile(csv_files[1]), sep = sep_char,
                              header = TRUE, row.names = 1, check.names = FALSE)
      message(sprintf("  [OK] %s - CSV/TSV (%d genes, %d cells)",
                      gsm_id, nrow(counts), ncol(counts)))
      return(as.matrix(counts))
    }, error = function(e) {
      message(sprintf("  [ERROR] %s - CSV read failed: %s", gsm_id, e$message))
      return(NULL)
    })
  }

  message(sprintf("  [SKIP] %s - unrecognised format", gsm_id))
  return(NULL)
}

# ==============================================================================
# 3. LOAD SAMPLES AND CREATE SEURAT OBJECTS
# ==============================================================================
cat("\n--- Loading samples ---\n")
seurat_list <- list()
load_stats  <- data.frame()

for (i in seq_len(nrow(gsm_mapping))) {
  gsm_id    <- gsm_mapping$GSM_ID[i]
  sample_id <- gsm_mapping$Sample_ID[i]
  condition <- gsm_mapping$Condition[i]

  cat(sprintf("\n[%d/%d] %s (%s - %s)\n", i, nrow(gsm_mapping), gsm_id, sample_id, condition))
  counts <- load_sample(gsm_id, data_dir)

  if (is.null(counts)) {
    load_stats <- rbind(load_stats, data.frame(
      GSM_ID = gsm_id, Sample_ID = sample_id, Condition = condition,
      Status = "FAILED", N_cells_raw = NA, N_genes = NA))
    next
  }

  seu <- tryCatch(
    CreateSeuratObject(counts = counts, project = sample_id,
                       min.cells = 3, min.features = 200),
    error = function(e) { message("  CreateSeuratObject failed: ", e$message); NULL }
  )

  if (is.null(seu)) {
    load_stats <- rbind(load_stats, data.frame(
      GSM_ID = gsm_id, Sample_ID = sample_id, Condition = condition,
      Status = "SEURAT_FAIL", N_cells_raw = ncol(counts), N_genes = nrow(counts)))
    next
  }

  seu$orig.ident <- sample_id
  seu$GSM_ID     <- gsm_id
  seu$Condition  <- condition

  load_stats <- rbind(load_stats, data.frame(
    GSM_ID = gsm_id, Sample_ID = sample_id, Condition = condition,
    Status = "OK", N_cells_raw = ncol(seu), N_genes = nrow(seu)))

  seurat_list[[sample_id]] <- seu
}

cat(sprintf("\n--- Loaded %d / %d samples ---\n", length(seurat_list), nrow(gsm_mapping)))
failed_samples <- load_stats[load_stats$Status != "OK", ]
if (nrow(failed_samples) > 0) {
  cat("\n[WARNING] Samples not loaded:\n"); print(failed_samples)
}
if (length(seurat_list) == 0) stop("No samples loaded. Check download (script 00).")

# ==============================================================================
# 4. COMPUTE QC METRICS AND PLOT (PRE-FILTER)
# ==============================================================================
cat("\n--- Computing QC metrics ---\n")

seurat_list <- lapply(seurat_list, function(seu) {
  seu[["percent.mt"]] <- PercentageFeatureSet(seu, pattern = "^MT-")
  seu[["percent.rb"]] <- PercentageFeatureSet(seu, pattern = "^RP[SL]")
  seu
})

qc_data <- do.call(rbind, lapply(names(seurat_list), function(nm) {
  seu <- seurat_list[[nm]]
  data.frame(Sample = seu$orig.ident, Condition = seu$Condition,
             nFeature = seu$nFeature_RNA, nCount = seu$nCount_RNA,
             pct_mt = seu$percent.mt, stringsAsFactors = FALSE)
}))

cat("Generating pre-filter QC plots...\n")

p_qc_feat <- ggplot(qc_data, aes(x = Sample, y = nFeature, fill = Condition)) +
  geom_violin(scale = "width", trim = TRUE) +
  geom_hline(yintercept = c(200, 6000), linetype = "dashed", color = "grey40") +
  scale_fill_manual(values = cond_colors) +
  labs(title = "Detected Genes per Sample — Pre-filter",
       subtitle = "Dashed lines: filter thresholds (200 – 6,000)",
       x = "Sample", y = "Number of detected genes") +
  theme_dfu(11) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p_qc_mt <- ggplot(qc_data, aes(x = Sample, y = pct_mt, fill = Condition)) +
  geom_violin(scale = "width", trim = TRUE) +
  geom_hline(yintercept = 20, linetype = "dashed", color = "firebrick") +
  scale_fill_manual(values = cond_colors) +
  labs(title = "Mitochondrial Gene % per Sample — Pre-filter",
       subtitle = "Dashed line: filter threshold (20%)",
       x = "Sample", y = "% Mitochondrial genes") +
  theme_dfu(11) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

p_qc_scatter <- ggplot(qc_data, aes(x = nCount, y = nFeature, color = pct_mt)) +
  geom_point(size = 0.3, alpha = 0.5) +
  scale_color_gradient(low = "steelblue", high = "firebrick", name = "% MT") +
  scale_x_log10() + scale_y_log10() +
  facet_wrap(~ Condition) +
  geom_hline(yintercept = c(200, 6000), linetype = "dashed", color = "grey40") +
  labs(title = "UMI Count vs Detected Genes",
       x = "UMI count (log10)", y = "Detected genes (log10)") +
  theme_dfu(10)

p_qc_panel <- (p_qc_feat / p_qc_mt) | p_qc_scatter
ggsave(file.path(plot_dir, "01_QC_prefilter.pdf"), p_qc_panel, width = 18, height = 12)
cat("  Saved: 01_QC_prefilter.pdf\n")

# ==============================================================================
# 5. HARD-THRESHOLD QC FILTER
# ==============================================================================
cat("\n--- Applying QC filters ---\n")
qc_stats <- data.frame()

seurat_list_filtered <- lapply(names(seurat_list), function(nm) {
  seu      <- seurat_list[[nm]]
  n_before <- ncol(seu)

  seu <- subset(seu,
                subset = nFeature_RNA >= 200 &
                         nFeature_RNA <= 6000 &
                         percent.mt   <  20)

  n_after  <- ncol(seu)
  n_remove <- n_before - n_after
  cat(sprintf("  %s: %d → %d cells (removed: %d, %.1f%%)\n",
              nm, n_before, n_after, n_remove, 100 * n_remove / n_before))

  qc_stats <<- rbind(qc_stats, data.frame(
    Sample_ID   = nm,
    Condition   = unique(seu$Condition),
    Pre_QCfilt  = n_before,
    Post_QCfilt = n_after,
    QC_removed  = n_remove,
    QC_pct      = round(100 * n_remove / n_before, 1)
  ))
  seu
})
names(seurat_list_filtered) <- names(seurat_list)

# ==============================================================================
# 6. DOUBLET DETECTION WITH scDblFinder
#
# WHY: QC filtering based on nFeature alone does not reliably remove doublets.
#      scDblFinder explicitly models the expected count distribution of doublets
#      by simulating artificial doublets from real cells, then trains a random
#      forest classifier to assign a doublet score to each barcode.
#
# WHEN: Applied per sample independently, on raw (non-normalised) counts,
#       AFTER hard QC filtering and BEFORE normalization / merge.
#
# EXPECTED DOUBLET RATE: typically 2-10% depending on loading density.
#      For 10x Genomics: ~1% per 1,000 cells loaded.
#
# REFERENCE: Germain et al. (2021) F1000Research 10:979
# ==============================================================================
cat("\n--- Doublet detection with scDblFinder ---\n")
cat("  Running independently on each sample (raw counts, pre-normalization)\n")

doublet_stats <- data.frame()

seurat_list_clean <- lapply(names(seurat_list_filtered), function(nm) {
  seu      <- seurat_list_filtered[[nm]]
  n_before <- ncol(seu)
  cat(sprintf("  [%s] %d cells...", nm, n_before))

  # Convert Seurat → SingleCellExperiment (required by scDblFinder)
  sce <- tryCatch(
    as.SingleCellExperiment(seu),
    error = function(e) {
      message(sprintf(" [ERROR] SCE conversion: %s", e$message)); NULL
    }
  )

  if (is.null(sce)) {
    cat(" skipped, keeping all cells.\n")
    seu$doublet_class <- "singlet"; seu$doublet_score <- NA_real_
    return(seu)
  }

  sce <- tryCatch(
    scDblFinder(sce, samples = NULL, BPPARAM = SerialParam()),
    error = function(e) {
      message(sprintf(" [ERROR] scDblFinder: %s", e$message)); NULL
    }
  )

  if (is.null(sce)) {
    cat(" skipped, keeping all cells.\n")
    seu$doublet_class <- "singlet"; seu$doublet_score <- NA_real_
    return(seu)
  }

  # Transfer labels back to Seurat metadata
  seu$doublet_class <- sce$scDblFinder.class   # "singlet" | "doublet"
  seu$doublet_score <- sce$scDblFinder.score   # continuous score 0–1

  n_dbl <- sum(seu$doublet_class == "doublet")
  cat(sprintf(" %d doublets (%.1f%%)\n", n_dbl, 100 * n_dbl / n_before))

  # Remove doublets
  seu_clean <- subset(seu, subset = doublet_class == "singlet")

  doublet_stats <<- rbind(doublet_stats, data.frame(
    Sample_ID    = nm,
    Condition    = unique(seu$Condition),
    Pre_doublet  = n_before,
    Doublets     = n_dbl,
    Doublet_pct  = round(100 * n_dbl / n_before, 1),
    Post_doublet = ncol(seu_clean)
  ))

  seu_clean
})
names(seurat_list_clean) <- names(seurat_list_filtered)

# ---- Merge QC + doublet stats and save ----
if (nrow(doublet_stats) > 0) {
  qc_stats_combined <- merge(
    qc_stats,
    doublet_stats[, c("Sample_ID","Doublets","Doublet_pct","Post_doublet")],
    by = "Sample_ID", all = TRUE
  )
  colnames(qc_stats_combined)[colnames(qc_stats_combined) == "Post_doublet"] <- "Final_cells"
  write.csv(qc_stats_combined, file.path(res_dir, "QC_stats_per_sample.csv"), row.names = FALSE)
  cat("\nQC + Doublet removal summary:\n"); print(qc_stats_combined)
} else {
  write.csv(qc_stats, file.path(res_dir, "QC_stats_per_sample.csv"), row.names = FALSE)
}

# ---- Doublet QC plots ----
if (nrow(doublet_stats) > 0) {

  # Plot 1: Doublet rate per sample
  p_dbl_pct <- ggplot(doublet_stats,
                       aes(x = reorder(Sample_ID, -Doublet_pct),
                           y = Doublet_pct, fill = Condition)) +
    geom_col(width = 0.7, color = "black", linewidth = 0.3) +
    geom_text(aes(label = sprintf("%.1f%%", Doublet_pct)),
              vjust = -0.4, size = 3, color = "black") +
    scale_fill_manual(values = cond_colors) +
    labs(title = "Doublet Rate per Sample (scDblFinder)",
         subtitle = "Predicted doublets removed from downstream analysis",
         x = "Sample", y = "Doublet rate (%)") +
    theme_dfu(11) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

  # Plot 2: Waterfall — cell counts across processing steps
  waterfall_df <- data.frame(
    Sample    = doublet_stats$Sample_ID,
    Condition = doublet_stats$Condition,
    After_loading        = qc_stats$Pre_QCfilt[match(doublet_stats$Sample_ID, qc_stats$Sample_ID)],
    After_QC_filter      = doublet_stats$Pre_doublet,
    After_doublet_removal = doublet_stats$Post_doublet
  )
  waterfall_long <- pivot_longer(waterfall_df,
                                  cols = c("After_loading","After_QC_filter","After_doublet_removal"),
                                  names_to = "Step", values_to = "N_cells")
  waterfall_long$Step <- factor(waterfall_long$Step,
                                 levels = c("After_loading","After_QC_filter","After_doublet_removal"),
                                 labels = c("After loading","After QC filter","After doublet removal"))

  p_waterfall <- ggplot(waterfall_long,
                         aes(x = Sample, y = N_cells, group = Step, color = Step)) +
    geom_line(linewidth = 0.7, alpha = 0.5) +
    geom_point(size = 2.5) +
    scale_color_manual(
      values = c("After loading"          = "grey55",
                 "After QC filter"        = "#FF9800",
                 "After doublet removal"  = "#2196F3"),
      name = "Processing step") +
    facet_wrap(~ Condition, scales = "free_x") +
    labs(title = "Cell Count at Each Processing Step",
         subtitle = "Per sample — all three conditions",
         x = "Sample", y = "Number of cells") +
    theme_dfu(11) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

  p_dbl_panel <- p_dbl_pct / p_waterfall
  ggsave(file.path(plot_dir, "02_Doublet_removal_QC.pdf"), p_dbl_panel, width = 14, height = 12)
  cat("  Saved: 02_Doublet_removal_QC.pdf\n")
}

cat(sprintf("\nTotal cells after QC + doublet removal: %d\n",
            sum(sapply(seurat_list_clean, ncol))))

# ==============================================================================
# 7. NORMALIZE AND FIND HVGs (per sample, before merge)
# ==============================================================================
cat("\n--- Normalization and HVG selection (per sample) ---\n")

seurat_list_norm <- lapply(seurat_list_clean, function(seu) {
  seu <- NormalizeData(seu, normalization.method = "LogNormalize",
                       scale.factor = 10000, verbose = FALSE)
  seu <- FindVariableFeatures(seu, selection.method = "vst",
                               nfeatures = 3000, verbose = FALSE)
  seu
})
cat("Normalization completed for all samples.\n")

# ==============================================================================
# 8. MERGE INTO ONE SEURAT OBJECT
# ==============================================================================
cat("\n--- Merging all samples ---\n")

if (length(seurat_list_norm) < 2) {
  seurat_merged <- seurat_list_norm[[1]]
} else {
  seurat_merged <- merge(
    x            = seurat_list_norm[[1]],
    y            = seurat_list_norm[-1],
    add.cell.ids = names(seurat_list_norm),
    project      = "GSE165816_DFU"
  )
}

# Seurat v5: join layers before scaling
if (inherits(seurat_merged[["RNA"]], "Assay5")) {
  seurat_merged <- JoinLayers(seurat_merged)
  cat("JoinLayers executed (Seurat v5)\n")
}

cat(sprintf("Merged object: %d genes × %d cells\n", nrow(seurat_merged), ncol(seurat_merged)))
cat("Cells per condition:\n"); print(table(seurat_merged$Condition))
cat("Cells per sample:\n");    print(table(seurat_merged$orig.ident))

# ==============================================================================
# 9. HVG SELECTION ON MERGED + SCALING + PCA
# ==============================================================================
cat("\n--- HVG selection, scaling and PCA on merged object ---\n")

seurat_merged <- FindVariableFeatures(seurat_merged, selection.method = "vst",
                                       nfeatures = 3000, verbose = FALSE)

if ("CCL4" %in% VariableFeatures(seurat_merged)) {
  cat("  [OK] CCL4 is among the highly variable genes\n")
} else {
  cat("  [INFO] CCL4 is NOT among top HVGs (still fully analysable downstream)\n")
}

seurat_merged <- ScaleData(seurat_merged,
                            features = VariableFeatures(seurat_merged),
                            verbose = FALSE)

seurat_merged <- RunPCA(seurat_merged,
                         features = VariableFeatures(seurat_merged),
                         npcs = 50, verbose = FALSE)
cat("PCA completed (50 PCs).\n")

# ==============================================================================
# 10. SAVE
# ==============================================================================
rds_path <- file.path(res_dir, "seurat_obj_pre_integration.rds")
saveRDS(seurat_merged, rds_path)

cat("\n=== PRE-PROCESSING SUMMARY ===\n")
cat(sprintf("  Samples successfully loaded : %d\n", length(seurat_list_norm)))
cat(sprintf("  Total cells (final)         : %d\n", ncol(seurat_merged)))
cat(sprintf("  Genes                       : %d\n", nrow(seurat_merged)))
cat(sprintf("  Highly variable genes       : %d\n", length(VariableFeatures(seurat_merged))))
cat(sprintf("  Object saved to             : %s\n", rds_path))
cat("\nCells per condition (final):\n")
print(table(seurat_merged$Condition))
cat("\nProceed with: 02_integration_clustering.R\n")
